-- CODE BY GIANLUCA TARASCONI UNDER CC3.0 LICENSE ATTRIBUTION-NONCOMMERCIAL-SHAREALIKE UNPORTED 
-- HTTP://RAWPATENTDATA.BLOGSPOT.COM FOR MORE INFO

-- UPDATED BY CHRISTIAN CHACUA FOR USE ON MYSQL 8 cchacua@gmail.com

-- 2018b VERSION


CREATE SCHEMA patstat2018b DEFAULT CHARACTER SET UTF8MB4 ;
USE patstat2018b;

-- -----------------------------------------------------------------------------
-- TLS201_APPLN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS201_APPLN;

CREATE TABLE TLS201_APPLN (
APPLN_ID INT(10) UNSIGNED,
APPLN_AUTH CHAR(2) NOT NULL DEFAULT '',
APPLN_NR VARCHAR(20) NOT NULL DEFAULT '',
APPLN_KIND CHAR(2) DEFAULT '',
APPLN_FILING_DATE DATE DEFAULT NULL,
APPLN_FILING_YEAR INT(4) DEFAULT NULL,
APPLN_NR_EPODOC VARCHAR(20) NOT NULL DEFAULT '',
APPLN_NR_ORIGINAL VARCHAR(100) NOT NULL DEFAULT '',
IPR_TYPE CHAR(2) DEFAULT '',
RECEIVING_OFFICE CHAR(2) NOT NULL DEFAULT '',
INTERNAT_APPLN_ID INT(11) DEFAULT NULL,
INT_PHASE CHAR(1) NOT NULL DEFAULT 'N',
REG_PHASE CHAR(1) NOT NULL DEFAULT 'N',
NAT_PHASE CHAR(1) NOT NULL DEFAULT 'N',
EARLIEST_FILING_DATE DATE NOT NULL DEFAULT '9999-12-31',
EARLIEST_FILING_YEAR INT(4) NOT NULL DEFAULT '9999',
EARLIEST_FILING_ID INT(11) NOT NULL DEFAULT '0',
EARLIEST_PUBLN_DATE DATE NOT NULL DEFAULT '9999-12-31',
EARLIEST_PUBLN_YEAR INT(4) NOT NULL DEFAULT '9999',
EARLIEST_PAT_PUBLN_ID INT(11) NOT NULL DEFAULT '0',
GRANTED CHAR(1) NOT NULL DEFAULT '',
DOCDB_FAMILY_ID INT(11) NOT NULL DEFAULT '0',
INPADOC_FAMILY_ID INT(11) NOT NULL DEFAULT '0',
DOCDB_FAMILY_SIZE INT(4) NOT NULL DEFAULT '0',
NB_CITING_DOCDB_FAM INT(4) NOT NULL DEFAULT '0',
NB_APPLICANTS INT(4) NOT NULL DEFAULT '0',
NB_INVENTORS INT(4) NOT NULL DEFAULT '0',
PRIMARY KEY (APPLN_ID),
KEY `DOCDB_FAMILY_ID` (`DOCDB_FAMILY_ID`)
) ENGINE=INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS202_APPLN_TITLE
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS202_APPLN_TITLE;

CREATE TABLE TLS202_APPLN_TITLE (
APPLN_ID INT(10) UNSIGNED NOT NULL,
APPLN_TITLE_LG VARCHAR(2) NOT NULL DEFAULT '',
APPLN_TITLE VARCHAR(3000) NOT NULL,
PRIMARY KEY (APPLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS203_APPLN_ABSTR
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS203_APPLN_ABSTR;

CREATE TABLE TLS203_APPLN_ABSTR(
APPLN_ID INT(10) UNSIGNED NOT NULL,
APPLN_ABSTRACT_LG VARCHAR(2) NOT NULL DEFAULT '',
APPLN_ABSTRACT VARCHAR(12000) NOT NULL,
PRIMARY KEY(APPLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
)
ENGINE = MYISAM
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS204_APPLN_PRIOR
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS204_APPLN_PRIOR;

CREATE TABLE TLS204_APPLN_PRIOR (
APPLN_ID INT(10) UNSIGNED NOT NULL,
PRIOR_APPLN_ID INT(10) UNSIGNED NOT NULL,
PRIOR_APPLN_SEQ_NR SMALLINT(4) UNSIGNED DEFAULT NULL,
PRIMARY KEY(APPLN_ID, PRIOR_APPLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
FOREIGN KEY(PRIOR_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS205_TECH_REL
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS205_TECH_REL;

CREATE TABLE TLS205_TECH_REL (
APPLN_ID INT(10) UNSIGNED NOT NULL,
TECH_REL_APPLN_ID INT(10) UNSIGNED NOT NULL,
PRIMARY KEY(APPLN_ID, TECH_REL_APPLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
FOREIGN KEY(TECH_REL_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS206_PERSON
-- -----------------------------------------------------------------------------
-- NOTE I DO NOT USE TLS906 I PUT TLS 206 WITH 906 DATA

DROP TABLE IF EXISTS TLS206_PERSON;

CREATE TABLE TLS206_PERSON (
PERSON_ID INT(10) UNSIGNED NOT NULL,
PERSON_NAME VARCHAR(300),
PERSON_ADDRESS VARCHAR(500),
PERSON_CTRY_CODE CHAR(2) NOT NULL,
NUTS VARCHAR(5) NOT NULL DEFAULT '',
NUTS_LEVEL INT(1) NOT NULL DEFAULT 9,
DOC_STD_NAME_ID INT(10) UNSIGNED NOT NULL,
DOC_STD_NAME VARCHAR(500),
PSN_ID INT(10) UNSIGNED NOT NULL,
PSN_NAME VARCHAR(500),
PSN_LEVEL INT(3) UNSIGNED NOT NULL,
PSN_SECTOR VARCHAR(50),
HAN_ID INT(10) UNSIGNED NOT NULL,
HAN_NAME VARCHAR(500),
HAN_HARMONIZED INT(3) UNSIGNED NOT NULL,
PRIMARY KEY (PERSON_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS207_PERS_APPLN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS207_PERS_APPLN;

CREATE TABLE TLS207_PERS_APPLN (
PERSON_ID INT(10) UNSIGNED NOT NULL,
APPLN_ID INT(10) UNSIGNED NOT NULL,
APPLT_SEQ_NR SMALLINT(4) UNSIGNED NOT NULL,
INVT_SEQ_NR SMALLINT(4) UNSIGNED NOT NULL,
PRIMARY KEY(PERSON_ID, APPLN_ID, APPLT_SEQ_NR, INVT_SEQ_NR),
FOREIGN KEY(PERSON_ID) REFERENCES TLS206_PERSON(PERSON_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS209_APPLN_IPC
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS209_APPLN_IPC;

CREATE TABLE TLS209_APPLN_IPC (
APPLN_ID INT(10) UNSIGNED NOT NULL,
IPC_CLASS_SYMBOL VARCHAR(16) NOT NULL,
IPC_CLASS_LEVEL CHAR(1),
IPC_VERSION DATE,
IPC_VALUE CHAR(1),
IPC_POSITION CHAR(1),
IPC_GENER_AUTH CHAR(2),
PRIMARY KEY(APPLN_ID, IPC_CLASS_SYMBOL),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS210_APPLN_N_CLS
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS210_APPLN_N_CLS;

CREATE TABLE TLS210_APPLN_N_CLS (
APPLN_ID  INT(10) UNSIGNED NOT NULL,
NAT_CLASS_SYMBOL   VARCHAR(16) NOT NULL,
PRIMARY KEY(APPLN_ID, NAT_CLASS_SYMBOL),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS211_PAT_PUBLN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS211_PAT_PUBLN;

CREATE TABLE TLS211_PAT_PUBLN (
PAT_PUBLN_ID INT(10) UNSIGNED NOT NULL,
PUBLN_AUTH CHAR(2) NOT NULL,
PUBLN_NR VARCHAR(15) NOT NULL,
PUBLN_NR_ORIGINAL VARCHAR(100) NOT NULL DEFAULT '',
PUBLN_KIND CHAR(2),
APPLN_ID INT(10) UNSIGNED NOT NULL,
PUBLN_DATE DATE,
PUBLN_LG CHAR(2),
PUBLN_FIRST_GRANT CHAR(1) NOT NULL DEFAULT '',
PUBLN_CLAIMS VARCHAR(4) NOT NULL,
PRIMARY KEY(PAT_PUBLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS212_CITATION
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS212_CITATION;

CREATE TABLE TLS212_CITATION (
PAT_PUBLN_ID INT(10) UNSIGNED NOT NULL,
CITN_REPLENISHED INT(10) NOT NULL DEFAULT 0,
CITN_ID  SMALLINT(4) UNSIGNED NOT NULL,
CITN_ORIGIN VARCHAR(5),
CITED_PAT_PUBLN_ID INT(10) UNSIGNED DEFAULT NULL,
CITED_APPLN_ID INT(10) UNSIGNED NOT NULL,
PAT_CITN_SEQ_NR  SMALLINT(4) UNSIGNED DEFAULT NULL,
CITED_NPL_PUBLN_ID INT(10) UNSIGNED NOT NULL,
NPL_CITN_SEQ_NR SMALLINT(4) UNSIGNED DEFAULT NULL,
CITN_GENER_AUTH  CHAR(2) NOT NULL,
PRIMARY KEY(PAT_PUBLN_ID, CITN_REPLENISHED, CITN_ID),
FOREIGN KEY(PAT_PUBLN_ID) REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
FOREIGN KEY(CITED_PAT_PUBLN_ID) REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID),
FOREIGN KEY(CITED_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
FOREIGN KEY(CITED_NPL_PUBLN_ID) REFERENCES TLS214_NPL_PUBLN(NPL_PUBLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS214_NPL_PUBLN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS214_NPL_PUBLN;

CREATE TABLE TLS214_NPL_PUBLN (
NPL_PUBLN_ID INT(10) UNSIGNED NOT NULL,
NPL_TYPE CHAR(1) NOT NULL DEFAULT '',
NPL_BIBLIO VARCHAR(4000) NOT NULL DEFAULT '',
NPL_AUTHOR VARCHAR(1000) NOT NULL DEFAULT '',
NPL_TITLE1 VARCHAR(1000) NOT NULL DEFAULT '',
NPL_TITLE2 VARCHAR(1000) NOT NULL DEFAULT '',
NPL_EDITOR VARCHAR(500) NOT NULL DEFAULT '',
NPL_VOLUME VARCHAR(50) NOT NULL DEFAULT '',
NPL_ISSUE VARCHAR(50) NOT NULL DEFAULT '',
NPL_PUBLN_DATE VARCHAR(8) NOT NULL DEFAULT '',
NPL_PUBLN_END_DATE VARCHAR(8) NOT NULL DEFAULT '',
NPL_PUBLISHER VARCHAR(500) NOT NULL DEFAULT '',
NPL_PAGE_FIRST VARCHAR(200) NOT NULL DEFAULT '',
NPL_PAGE_LAST VARCHAR(200) NOT NULL DEFAULT '',
NPL_ABSTRACT_NR VARCHAR(50) NOT NULL DEFAULT '',
NPL_DOI VARCHAR(500) NOT NULL DEFAULT '',
NPL_ISBN VARCHAR(30) NOT NULL DEFAULT '',
NPL_ISSN VARCHAR(30) NOT NULL DEFAULT '',
ONLINE_AVAILABILITY VARCHAR(500) NOT NULL DEFAULT '',	
ONLINE_CLASSIFICATION VARCHAR(3) NOT NULL DEFAULT '',
ONLINE_SEARCH_DATE VARCHAR(8) NOT NULL DEFAULT '',
PRIMARY KEY(NPL_PUBLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS215_CITN_CATEG
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS215_CITN_CATEG;

CREATE TABLE TLS215_CITN_CATEG (
PAT_PUBLN_ID INT(10) UNSIGNED NOT NULL,
CITN_REPLENISHED INT(10) NOT NULL DEFAULT 0,
CITN_ID SMALLINT(4) UNSIGNED NOT NULL,
CITN_CATEG CHAR(1) NOT NULL,
PRIMARY KEY(PAT_PUBLN_ID, CITN_REPLENISHED, CITN_ID, CITN_CATEG),
FOREIGN KEY(PAT_PUBLN_ID, CITN_REPLENISHED, CITN_ID) REFERENCES TLS212_CITATION(PAT_PUBLN_ID, CITN_REPLENISHED, CITN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS216_APPLN_CONTN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS216_APPLN_CONTN;

CREATE TABLE TLS216_APPLN_CONTN (
APPLN_ID INT(10) UNSIGNED NOT NULL,
PARENT_APPLN_ID INT(10) UNSIGNED NOT NULL,
CONTN_TYPE CHAR(3),
PRIMARY KEY(APPLN_ID, PARENT_APPLN_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID),
FOREIGN KEY(PARENT_APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS222_APPLN_JP_CLASS
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS222_APPLN_JP_CLASS;

CREATE TABLE TLS222_APPLN_JP_CLASS (
APPLN_ID INT(10) UNSIGNED NOT NULL,
JP_CLASS_SCHEME VARCHAR(6) NOT NULL,
JP_CLASS_SYMBOL VARCHAR(50) NOT NULL,
PRIMARY KEY(APPLN_ID, JP_CLASS_SCHEME, JP_CLASS_SYMBOL),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS223_APPLN_DOCUS
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS223_APPLN_DOCUS;

CREATE TABLE TLS223_APPLN_DOCUS (
APPLN_ID INT(10) UNSIGNED NOT NULL,
DOCUS_CLASS_SYMBOL VARCHAR(50) NOT NULL,
PRIMARY KEY(APPLN_ID, DOCUS_CLASS_SYMBOL),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS224_APPLN_CPC
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS224_APPLN_CPC;

CREATE TABLE TLS224_APPLN_CPC(
APPLN_ID INT(10) UNSIGNED NOT NULL,
CPC_CLASS_SYMBOL VARCHAR(19) NOT NULL DEFAULT '',
CPC_SCHEME VARCHAR(5) NOT NULL DEFAULT '',
CPC_VERSION DATE NOT NULL DEFAULT '9999-12-31',
CPC_VALUE CHAR(1) NOT NULL DEFAULT '',
CPC_POSITION CHAR(1) NOT NULL DEFAULT '',
CPC_GENER_AUTH CHAR(2) NOT NULL DEFAULT '',
PRIMARY KEY(APPLN_ID, CPC_CLASS_SYMBOL, CPC_SCHEME),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN(APPLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS226_PERSON_ORIG
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS226_PERSON_ORIG;

CREATE TABLE TLS226_PERSON_ORIG(
PERSON_ORIG_ID INT(10) UNSIGNED NOT NULL,
PERSON_ID INT(10) UNSIGNED NOT NULL,
SOURCE CHAR(5) NOT NULL DEFAULT '',
SOURCE_VERSION VARCHAR(10) NOT NULL DEFAULT '',
NAME_FREEFORM VARCHAR(500) NOT NULL DEFAULT '',
LAST_NAME VARCHAR(400) NOT NULL DEFAULT '',
FIRST_NAME VARCHAR(200) NOT NULL DEFAULT '',
MIDDLE_NAME VARCHAR(50) NOT NULL DEFAULT '',
ADDRESS_FREEFORM VARCHAR(1000) NOT NULL DEFAULT '',
ADDRESS_1 VARCHAR(500) NOT NULL DEFAULT '',
ADDRESS_2 VARCHAR(500) NOT NULL DEFAULT '',
ADDRESS_3 VARCHAR(500) NOT NULL DEFAULT '',
ADDRESS_4 VARCHAR(500) NOT NULL DEFAULT '',
ADDRESS_5 VARCHAR(500) NOT NULL DEFAULT '',
STREET VARCHAR(500) NOT NULL DEFAULT '',
CITY VARCHAR(200) NOT NULL DEFAULT '',
ZIP_CODE VARCHAR(30) NOT NULL DEFAULT '',
STATE CHAR(2) NOT NULL DEFAULT '',
PERSON_CTRY_CODE CHAR(2) NOT NULL DEFAULT '',
RESIDENCE_CTRY_CODE CHAR(2) NOT NULL DEFAULT '',
ROLE VARCHAR(2) NOT NULL DEFAULT '',
PRIMARY KEY(PERSON_ORIG_ID),
FOREIGN KEY(PERSON_ID) REFERENCES TLS206_PERSON(PERSON_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS227_PERS_PUBLN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS227_PERS_PUBLN;

CREATE TABLE TLS227_PERS_PUBLN(
PERSON_ID INT(10) UNSIGNED NOT NULL,
PAT_PUBLN_ID INT(10) UNSIGNED NOT NULL,
APPLT_SEQ_NR SMALLINT NOT NULL,
INVT_SEQ_NR SMALLINT NOT NULL,
PRIMARY KEY(PERSON_ID, PAT_PUBLN_ID, APPLT_SEQ_NR, INVT_SEQ_NR),
FOREIGN KEY(PERSON_ID) REFERENCES TLS206_PERSON(PERSON_ID),
FOREIGN KEY(PAT_PUBLN_ID) REFERENCES TLS211_PAT_PUBLN(PAT_PUBLN_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS228_DOCDB_FAM_CITN
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS228_DOCDB_FAM_CITN;

CREATE TABLE TLS228_DOCDB_FAM_CITN(
DOCDB_FAMILY_ID INT(11) NOT NULL DEFAULT 0,
CITED_DOCDB_FAMILY_ID INT(1) NOT NULL DEFAULT 0,
PRIMARY KEY(DOCDB_FAMILY_ID, CITED_DOCDB_FAMILY_ID),
FOREIGN KEY(DOCDB_FAMILY_ID) REFERENCES TLS201_APPLN(DOCDB_FAMILY_ID),
FOREIGN KEY(CITED_DOCDB_FAMILY_ID) REFERENCES TLS201_APPLN(DOCDB_FAMILY_ID)
)
ENGINE = INNODB;

-- -----------------------------------------------------------------------------
-- TLS902_IPC_NACE2
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS902_IPC_NACE2;

CREATE TABLE TLS902_IPC_NACE2(
IPC VARCHAR(8) NOT NULL DEFAULT '',
NOT_WITH_IPC VARCHAR(8) NOT NULL DEFAULT '',
UNLESS_WITH_IPC VARCHAR(8) NOT NULL DEFAULT '',
NACE2_CODE VARCHAR(5) NOT NULL DEFAULT '',
NACE2_WEIGHT REAL NOT NULL DEFAULT 1,
NACE2_DESCR VARCHAR(150) NOT NULL DEFAULT '',
PRIMARY KEY(IPC, NOT_WITH_IPC, UNLESS_WITH_IPC, NACE2_CODE),
INDEX (NACE2_CODE)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS229_APPLN_NACE2
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS229_APPLN_NACE2;

CREATE TABLE TLS229_APPLN_NACE2(
APPLN_ID INT(10) UNSIGNED NOT NULL,
NACE2_CODE VARCHAR(5) NOT NULL DEFAULT '',
WEIGHT REAL NOT NULL DEFAULT 1,
PRIMARY KEY(APPLN_ID, NACE2_CODE),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN (APPLN_ID),
FOREIGN KEY(NACE2_CODE) REFERENCES TLS902_IPC_NACE2(NACE2_CODE)
)
ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS901_TECHN_FIELD_IPC
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS901_TECHN_FIELD_IPC;

CREATE TABLE TLS901_TECHN_FIELD_IPC(
IPC_MAINGROUP_SYMBOL VARCHAR(8) NOT NULL DEFAULT '',
TECHN_FIELD_NR INT(4) NOT NULL DEFAULT 0,
TECHN_SECTOR VARCHAR(50) NOT NULL DEFAULT '',
TECHN_FIELD VARCHAR(50) NOT NULL DEFAULT '',
PRIMARY KEY (IPC_MAINGROUP_SYMBOL),
INDEX (TECHN_FIELD_NR)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS230_APPLN_TECHN_FIELD
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS230_APPLN_TECHN_FIELD;

CREATE TABLE TLS230_APPLN_TECHN_FIELD(
APPLN_ID INT(10) UNSIGNED NOT NULL,
TECHN_FIELD_NR INT(4) NOT NULL DEFAULT 0,
WEIGHT REAL NOT NULL DEFAULT 1,
PRIMARY KEY(APPLN_ID, TECHN_FIELD_NR),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN (APPLN_ID),
FOREIGN KEY(TECHN_FIELD_NR) REFERENCES TLS901_TECHN_FIELD_IPC(TECHN_FIELD_NR))
ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS803_LEGAL_EVENT_CODE
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS803_LEGAL_EVENT_CODE;

CREATE TABLE TLS803_LEGAL_EVENT_CODE(
EVENT_AUTH VARCHAR(2) NOT NULL DEFAULT '',
EVENT_CODE VARCHAR(4) NOT NULL DEFAULT '',
EVENT_IMPACT VARCHAR(1) NOT NULL DEFAULT '',
EVENT_DESCR VARCHAR(250) NOT NULL DEFAULT '',
EVENT_DESCR_ORIG VARCHAR(250) NOT NULL DEFAULT '',
EVENT_CATEGORY_CODE CHAR(1) NOT NULL DEFAULT '',
EVENT_CATEGORY_TITLE VARCHAR(100) NOT NULL DEFAULT '',
PRIMARY KEY(EVENT_AUTH, EVENT_CODE)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS231_INPADOC_LEGAL_EVENT
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS231_INPADOC_LEGAL_EVENT;

CREATE TABLE TLS231_INPADOC_LEGAL_EVENT(
EVENT_ID INT(10) UNSIGNED NOT NULL,
APPLN_ID INT(10) UNSIGNED NOT NULL,
EVENT_SEQ_NR INT(5) UNSIGNED NOT NULL,
EVENT_TYPE CHAR(3) NOT NULL DEFAULT '	',
EVENT_AUTH CHAR(2) NOT NULL DEFAULT '  ',
EVENT_CODE VARCHAR(4)  NOT NULL DEFAULT '',
EVENT_FILING_DATE DATE NOT NULL DEFAULT '9999-12-31',
EVENT_PUBLN_DATE DATE NOT NULL DEFAULT '9999-12-31',
EVENT_EFFECTIVE_DATE DATE NOT NULL DEFAULT '9999-12-31',
EVENT_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
REF_DOC_AUTH CHAR(2) NOT NULL DEFAULT '  ',
REF_DOC_NR VARCHAR(20) NOT NULL DEFAULT '',
REF_DOC_KIND CHAR(2) NOT NULL DEFAULT '  ',
REF_DOC_DATE DATE NOT NULL DEFAULT '9999-12-31',
REF_DOC_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
PARTY_TYPE VARCHAR(3) NOT NULL DEFAULT '	',
PARTY_SEQ_NR  INT(5) NOT NULL DEFAULT 0,
PARTY_NEW VARCHAR(1000) NOT NULL DEFAULT '',
PARTY_OLD VARCHAR(1000) NOT NULL DEFAULT '',
SPC_NR VARCHAR(40) NOT NULL DEFAULT '',
SPC_FILING_DATE DATE NOT NULL DEFAULT '9999-12-31',
SPC_PATENT_EXPIRY_DATE DATE NOT NULL DEFAULT '9999-12-31',
SPC_EXTENSION_DATE DATE NOT NULL DEFAULT '9999-12-31',
SPC_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
DESIGNATED_STATES VARCHAR(1000) NOT NULL DEFAULT '',
EXTENSION_STATES VARCHAR(30) NOT NULL DEFAULT '',
FEE_COUNTRY CHAR(2) NOT NULL DEFAULT '  ',
FEE_PAYMENT_DATE DATE NOT NULL DEFAULT '9999-12-31',
FEE_RENEWAL_YEAR  INT(5) NOT NULL DEFAULT '9999',
FEE_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
LAPSE_COUNTRY CHAR(2) NOT NULL DEFAULT '  ',
LAPSE_DATE DATE NOT NULL DEFAULT '9999-12-31',
LAPSE_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
REINSTATE_COUNTRY CHAR(2) NOT NULL DEFAULT '  ',
REINSTATE_DATE DATE NOT NULL DEFAULT '9999-12-31',
REINSTATE_TEXT VARCHAR(1000) NOT NULL DEFAULT '',
CLASS_SCHEME VARCHAR(4) NOT NULL DEFAULT '',
CLASS_SYMBOL VARCHAR(50) NOT NULL DEFAULT '', 
PRIMARY KEY(EVENT_ID),
FOREIGN KEY(APPLN_ID) REFERENCES TLS201_APPLN (APPLN_ID),
FOREIGN KEY(EVENT_AUTH, EVENT_CODE) REFERENCES TLS803_LEGAL_EVENT_CODE(EVENT_AUTH, EVENT_CODE)
)
ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS801_COUNTRY
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS801_COUNTRY;

CREATE TABLE TLS801_COUNTRY(
CTRY_CODE CHAR(2) NOT NULL,
ISO_ALPHA3 CHAR(3),
ST3_NAME VARCHAR(100),
STATE_INDICATOR CHAR(1),
CONTINENT VARCHAR(25),
EU_MEMBER CHAR(1),
EPO_MEMBER CHAR(1),
OECD_MEMBER CHAR(1),
DISCONTINUED CHAR(1),
PRIMARY KEY(CTRY_CODE)
)
ENGINE = INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

-- -----------------------------------------------------------------------------
-- TLS904_NUTS
-- -----------------------------------------------------------------------------

DROP TABLE IF EXISTS TLS904_NUTS;

CREATE TABLE TLS904_NUTS(
NUTS VARCHAR(5) NOT NULL DEFAULT '',
NUTS_LEVEL VARCHAR(250) NOT NULL DEFAULT '',
NUTS_LABEL VARCHAR(250) NOT NULL DEFAULT '',
PRIMARY KEY (NUTS)
)
ENGINE = INNODB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;
