-- PATSTAT LOAD TABLES

-- 2018b VERSION

-- By Christian Chacua cchacua@gmail.com
-- mysql -h "localhost" -u "root" --local-infile patstat2018b -p 

USE patstat2018b;

SHOW VARIABLES LIKE "local_infile";
SET GLOBAL local_infile = 'ON';
SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
SET SQL_LOG_BIN=0;


-- -----------------------------------------------------------------------------
-- TLS201_APPLN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part01.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part02.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part03.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part04.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part05.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part06.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part07.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part08.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part09.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls201_part10.txt' INTO TABLE TLS201_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS202_APPLN_TITLE
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls202_part01.txt' INTO TABLE TLS202_APPLN_TITLE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls202_part02.txt' INTO TABLE TLS202_APPLN_TITLE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls202_part03.txt' INTO TABLE TLS202_APPLN_TITLE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part01.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part02.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS203_APPLN_ABSTR
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part03.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part04.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part05.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part06.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part07.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part08.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part09.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part10.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part11.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part12.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part13.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part14.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part15.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part16.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part17.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part18.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part19.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part20.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part21.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part22.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part23.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part24.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part25.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part26.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part27.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part28.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part29.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part30.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part31.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part32.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part33.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls203_part34.txt' INTO TABLE TLS203_APPLN_ABSTR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS204_APPLN_PRIOR
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls204_part01.txt' INTO TABLE TLS204_APPLN_PRIOR 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS205_TECH_REL
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls205_part01.txt' INTO TABLE TLS205_TECH_REL 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS206_PERSON
-- -----------------------------------------------------------------------------
-- NOTE: TLS906 DATA IS USED IN TLS206

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls906_part01.txt' INTO TABLE TLS206_PERSON 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls906_part02.txt' INTO TABLE TLS206_PERSON 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls906_part03.txt' INTO TABLE TLS206_PERSON 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls906_part04.txt' INTO TABLE TLS206_PERSON 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls906_part05.txt' INTO TABLE TLS206_PERSON 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS207_PERS_APPLN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls207_part01.txt' INTO TABLE TLS207_PERS_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls207_part02.txt' INTO TABLE TLS207_PERS_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls207_part03.txt' INTO TABLE TLS207_PERS_APPLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS209_APPLN_IPC
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part01.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part02.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part03.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part04.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part05.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part06.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part07.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls209_part08.txt' INTO TABLE TLS209_APPLN_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS210_APPLN_N_CLS
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls210_part01.txt' INTO TABLE TLS210_APPLN_N_CLS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS211_PAT_PUBLN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls211_part01.txt' INTO TABLE TLS211_PAT_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls211_part02.txt' INTO TABLE TLS211_PAT_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls211_part03.txt' INTO TABLE TLS211_PAT_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls211_part04.txt' INTO TABLE TLS211_PAT_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls211_part05.txt' INTO TABLE TLS211_PAT_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;


-- -----------------------------------------------------------------------------
-- TLS212_CITATION
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part01.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part02.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part03.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part04.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part05.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part06.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part07.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls212_part08.txt' INTO TABLE TLS212_CITATION 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS214_NPL_PUBLN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls214_part01.txt' INTO TABLE TLS214_NPL_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls214_part02.txt' INTO TABLE TLS214_NPL_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls214_part03.txt' INTO TABLE TLS214_NPL_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls214_part04.txt' INTO TABLE TLS214_NPL_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls214_part05.txt' INTO TABLE TLS214_NPL_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS215_CITN_CATEG
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls215_part01.txt' INTO TABLE TLS215_CITN_CATEG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS216_APPLN_CONTN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls216_part01.txt' INTO TABLE TLS216_APPLN_CONTN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS222_APPLN_JP_CLASS
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part01.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part02.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part03.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part04.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part05.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part06.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls222_part07.txt' INTO TABLE TLS222_APPLN_JP_CLASS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS223_APPLN_DOCUS
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls223_part01.txt' INTO TABLE TLS223_APPLN_DOCUS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS224_APPLN_CPC
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part01.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part02.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part03.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part04.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part05.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part06.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part07.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls224_part08.txt' INTO TABLE TLS224_APPLN_CPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS226_PERSON_ORIG
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls226_part01.txt' INTO TABLE TLS226_PERSON_ORIG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls226_part02.txt' INTO TABLE TLS226_PERSON_ORIG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls226_part03.txt' INTO TABLE TLS226_PERSON_ORIG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls226_part04.txt' INTO TABLE TLS226_PERSON_ORIG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls226_part05.txt' INTO TABLE TLS226_PERSON_ORIG 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS227_PERS_PUBLN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls227_part01.txt' INTO TABLE TLS227_PERS_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls227_part02.txt' INTO TABLE TLS227_PERS_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls227_part03.txt' INTO TABLE TLS227_PERS_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls227_part04.txt' INTO TABLE TLS227_PERS_PUBLN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS228_DOCDB_FAM_CITN
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls228_part01.txt' INTO TABLE TLS228_DOCDB_FAM_CITN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls228_part02.txt' INTO TABLE TLS228_DOCDB_FAM_CITN 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS229_APPLN_NACE2
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls229_part01.txt' INTO TABLE TLS229_APPLN_NACE2 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls229_part02.txt' INTO TABLE TLS229_APPLN_NACE2 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS230_APPLN_TECHN_FIELD
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls230_part01.txt' INTO TABLE TLS230_APPLN_TECHN_FIELD 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls230_part02.txt' INTO TABLE TLS230_APPLN_TECHN_FIELD 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS231_INPADOC_LEGAL_EVENT
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part01.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part02.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part03.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part04.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part05.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part06.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part07.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part08.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part09.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part10.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part11.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part12.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part13.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part14.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part15.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part16.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part17.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part18.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part19.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part20.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part21.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part22.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part23.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part24.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part25.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part26.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part27.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part28.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part29.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part30.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part31.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part32.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part33.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
LOAD DATA LOCAL INFILE '/patstat2018b/data/tls231_part34.txt' INTO TABLE TLS231_INPADOC_LEGAL_EVENT 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS801_COUNTRY
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls801_part01.txt' INTO TABLE TLS801_COUNTRY 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS803_LEGAL_EVENT_CODE
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls803_part01.txt' INTO TABLE TLS803_LEGAL_EVENT_CODE 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS901_TECHN_FIELD_IPC
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls901_part01.txt' INTO TABLE TLS901_TECHN_FIELD_IPC 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS902_IPC_NACE2
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls902_part01.txt' INTO TABLE TLS902_IPC_NACE2 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;

-- -----------------------------------------------------------------------------
-- TLS904_NUTS
-- -----------------------------------------------------------------------------

LOAD DATA LOCAL INFILE '/patstat2018b/data/tls904_part01.txt' INTO TABLE TLS904_NUTS 
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'  ESCAPED BY ''
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;
SHOW WARNINGS;
